// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCmnXFBOfE_bOyuq2yFxtprFzh97aYFgo',
    appId: '1:1036772380453:web:141a1625432a6c86f314cc',
    messagingSenderId: '1036772380453',
    projectId: 'tpfinal-emanuelpaige',
    authDomain: 'tpfinal-emanuelpaige.firebaseapp.com',
    storageBucket: 'tpfinal-emanuelpaige.appspot.com',
    measurementId: 'G-L2283SF7RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGz0YlJosi87OSXOCS082SQr5F46gRNw4',
    appId: '1:1036772380453:android:0c1e6f8d452518a1f314cc',
    messagingSenderId: '1036772380453',
    projectId: 'tpfinal-emanuelpaige',
    storageBucket: 'tpfinal-emanuelpaige.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWXuvq_O_-KwM-YzSnLotsGc1LM5z4f8o',
    appId: '1:1036772380453:ios:07a495e496d69392f314cc',
    messagingSenderId: '1036772380453',
    projectId: 'tpfinal-emanuelpaige',
    storageBucket: 'tpfinal-emanuelpaige.appspot.com',
    iosBundleId: 'com.example.gestionClasse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWXuvq_O_-KwM-YzSnLotsGc1LM5z4f8o',
    appId: '1:1036772380453:ios:07a495e496d69392f314cc',
    messagingSenderId: '1036772380453',
    projectId: 'tpfinal-emanuelpaige',
    storageBucket: 'tpfinal-emanuelpaige.appspot.com',
    iosBundleId: 'com.example.gestionClasse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCmnXFBOfE_bOyuq2yFxtprFzh97aYFgo',
    appId: '1:1036772380453:web:95e1acf249546025f314cc',
    messagingSenderId: '1036772380453',
    projectId: 'tpfinal-emanuelpaige',
    authDomain: 'tpfinal-emanuelpaige.firebaseapp.com',
    storageBucket: 'tpfinal-emanuelpaige.appspot.com',
    measurementId: 'G-EMNF6C7VLD',
  );

}